include $(THEOS)/makefiles/common.mk

TOOL_NAME = VCNNetworkDaemonLauncher

VCNNetworkDaemonLauncher_FILES = main.c
VCNNetworkDaemonLauncher_INSTALL_PATH = /usr/libexec
VCNNetworkDaemonLauncher_CODESIGN_FLAGS = -Sentitlements.plist

include $(THEOS_MAKE_PATH)/tool.mk
