include $(THEOS)/makefiles/common.mk

TWEAK_NAME = VCNextNetworkCompat

VCNextNetworkCompat_FILES = Tweak.xm
VCNextNetworkCompat_FRAMEWORKS = Foundation CoreFoundation
VCNextNetworkCompat_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
