include $(THEOS)/makefiles/common.mk

TWEAK_NAME = VCNextBrandUI

VCNextBrandUI_FILES = Tweak.xm
VCNextBrandUI_FRAMEWORKS = Foundation CoreFoundation UIKit
VCNextBrandUI_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
